name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  installer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer tests
        run: make test-installer
